[project]
name = "frappe_vault"
authors = [
    { name = "Frappe Vault", email = "hello@example.com"}
]
description = "A Frappe-based password and secrets management application"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "frappe"
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.dev-dependencies]
# List any dev dependencies here

[tool.ruff]
line-length = 110
target-version = "py310"

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "I",
    "UP",
    "B",
]
ignore = [
    "E501"  # line too long
]
